---
language: php

php:
  - 7.4
  - 8.0

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - composer run test:coverage

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover build/coverage/clover.xml
